#!/bin/sh

NPMRC=~/.npmrc
NPMRC_NAMED=$NPMRC.$2

save () {
  echo "; config for $1" > $NPMRC_NAMED \
    && cat $NPMRC >> $NPMRC_NAMED \
    && echo "$NPMRC_NAMED saved successfully" \
    || (echo "Failed to save $NPMRC_NAMED" && return 1)
}

load () {
  cp $NPMRC_NAMED $NPMRC \
    && echo "Config for $1 successfully loaded" \
    || (echo "Failed to load $NPMRC_NAMED" && return 1)
}

list () {
  ls -a ~ | grep .npmrc.
}

install () {
  cp ./npmrc-do /usr/local/bin/npmrc-do \
    && chmod +x /usr/local/bin/npmrc-do \
    && echo "npmrc-do installed successfully" \
    || (echo "failed to install npmrc-do" && return 1)
}

remove () {
  rm $NPMRC_NAMED \
    && echo "Config for $1 removed" \
    || (echo "Failed to remove config for $1" && return 1)
}

current () {
  cat $NPMRC
}

uninstall () {
  rm /usr/local/bin/npmrc-do \
    && echo "npmrc-do successfully uninstalled" \
    || (echo "Failed to uninstall npmrc-do" && return 1)
}

help () {
  echo "Syntax:"
  echo "npmrc-do [command] [name]\n"
  echo "Available commands:"
  echo "list (default) - list all profiles in your home directory"
  echo "save - save current profile with name [name]"
  echo "load - load profile with name [name]"
  echo "remove - remove saved profile with name [name]"
  echo "current - output content of current .npmrc"
  echo "install - inspall script to /usr/local/bin (Admin permissions required)"
  echo "uninstall - remove script from /usr/local/bin"
  echo "help - output this help"
}

case "$1" in
"save"     ) save $2 || exit 1;;
"load"     ) load $2 || exit 1;;
"remove"   ) remove $2 || exit 1;;
"current"  ) current || exit 1;;
"install"  ) install || exit 1;;
"uninstall") uninstall || exit 1;;
"list" | "") list || exit 1;;
"help"     ) help || exit 1;;
*          ) help && exit 1;;
esac

exit 0
